apiVersion: v1
kind: Service
metadata:
  name: esnode166-service
  namespace: elasticsearch
spec:
  selector:
    app: elasticsearch
    node: elasticsearch7
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 31091
    name: a1
  - protocol: TCP
    port: 9300
    targetPort: 9300
    nodePort: 31093
    name: b1
  type: NodePort

