[plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.1.168:5000"]
  endpoint = ["https://192.168.1.168:5000"]

[plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.1.168:5000".tls]
  ca_file = "/ca.crt"

