apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-deployment
  namespace: router  # Add namespace
  labels:
    app: ic
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: ic
  template:
    metadata:
      labels:
        app: ic
    spec:
      nodeSelector:
        nodegroup: router  # Ensure pods run on nodes labeled with "nodegroup=middleware"
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"  # Update to NoExecute to match the taint on the node
      containers:
      - name: ic
        image: 192.168.1.168:5000/beacon:23oct2024D
        ports:
        - containerPort: 20000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: id
          value: "1"
        - name: _JAVA_OPTIONS
          value: "-Xmx256m -Xms256m"
        - name: module
          value: "ic"
        - name: hostip
          value: "192.168.1.168"
        - name: segment
          value: "chk3s"
        - name: profile
          value: "cat"
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ic-service
  namespace: router  # Add namespace
spec:
  type: NodePort
  selector:
    app: ic
  ports:
    - protocol: TCP
      port: 20000        # Internal port of the service
      targetPort: 20000   # Container's port
      nodePort: 32000     # External port on the node

---
