# /etc/rancher/k3s/config.yaml

# Specify the server's advertise address
advertise-address: "192.168.1.168"

# Enable the API server to listen on all interfaces
tls-san:
  - "0.0.0.0"
  - "192.168.1.168"

# Set other server options as needed
disable:
  - servicelb
  - metrics-server

# Enable specific features or plugins
kube-apiserver-arg:
  - "enable-admission-plugins=NodeRestriction"
  - "authorization-mode=AlwaysAllow"

# Configure etcd or other storage options if needed
datastore:
  endpoint: "sqlite:///var/lib/rancher/k3s/data.db"

# Set the cluster domain and network options if needed
cluster-domain: "cluster.local"
cni: "flannel"

# Specify additional options or configurations
write-kubeconfig-mode: "0644"

