# redis-accountsync-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-smppconsumer-pv
  namespace: redis
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-smppconsumer-storage
  local:
    path: /home/redisdata/smppconsumerredis # Adjust this to the path on your node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - redis6  # Specify the node where PV should be created
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-smppconsumer-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: redis-smppconsumer-storage

