# redis-accountsync-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-smppconcate-deployment
  namespace: redis
  labels:
    app: redis-smppconcate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-smppconcate
  template:
    metadata:
      labels:
        app: redis-smppconcate
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Exists"
        effect: "NoExecute"
      nodeSelector:
        kubernetes.io/hostname: redisnode177 # Specify the node by its hostname
      containers:
      - name: redis-smppconcate
        image: 192.168.1.168:5000/redis:6.0-alpine3.12
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-smppconcate-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-smppconcate-service
  namespace: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30013
  selector:
    app: redis-smppconcate
