apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpclienthandover-deployment
  namespace: dnpost  # Add namespace
  labels:
    app: httpclienthandoverapp
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: httpclienthandoverapp
  template:
    metadata:
      labels:
        app: httpclienthandoverapp
    spec:
      nodeSelector:
        nodegroup: dnpost  # Ensure pods run on nodes labeled with "nodegroup=middleware"
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"  # Update to NoExecute to match the taint on the node
      containers:
      - name: httpclienthandovercontainer
        image: 192.168.1.168:5000/beacon:07oct2024
        ports:
        - containerPort: 20000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            cpu: "4"
            memory: "3Gi"
        env:
        - name: id
          value: "1"
        - name: module
          value: "httpclienthandover"
        - name: modvalue
          value: "0,1,2,3"
        - name: cluster.names
          value: "trans,bulk,otp"
        - name: concat.redis.index
          value: "0,1,2,3"
        - name: cluster
          value: "trans,bulk,otp"
        - name: hostip
          value: "192.168.1.168"
        - name: segment
          value: "chk3s"
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: httpclienthandover-service
  namespace: dnpost  # Add namespace
spec:
  type: NodePort
  selector:
    app: httpclienthandoverapp
  ports:
    - protocol: TCP
      port: 20000        # Internal port of the service
      targetPort: 20000   # Container's port
      nodePort: 32005    # External port on the node
