apiVersion: v1
kind: Service
metadata:
  name: esnode167-service
  namespace: elasticsearch
spec:
  selector:
    app: elasticsearch
    node: esnode167
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 32091
    name: a1
  - protocol: TCP
    port: 9300
    targetPort: 9300
    nodePort: 32093
    name: b1
  type: NodePort

