# elasticsearch-deployment-node1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esnode167
  namespace: elasticsearch  # Add your namespace here
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        node: esnode167
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Exists"
        effect: "NoExecute"
      nodeSelector:
        kubernetes.io/hostname: esnode167 # Specify the node by its hostname
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: "multi-node"
        - name: xpack.security.enabled
          value: "false"
        - name: cluster.initial_master_nodes
          value: "esnode166,esnode167"
        - name: discovery.seed_hosts
          value: "esnode166,esnode167"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-pvc-167
