apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-166
  namespace: elasticsearch
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es166
  hostPath:
    path: "/home/esdata"  # Adjust this path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - esnode166 # Replace with the actual node name or label
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-167
  namespace: elasticsearch
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es167
  hostPath:
    path: "/home/esdata"  # Adjust this path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - esnode167 # Replace with the actual node name or label

