apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  namespace: http  # Add namespace
  labels:
    app: http
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      nodeSelector:
        nodegroup: interface  # Ensure pods run on nodes labeled with "nodegroup=middleware"
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"  # Update to NoExecute to match the taint on the node
      containers:
      - name: http
        image: 10.122.0.2:5000/beacontomcat:09nov2024A
        ports:
        - containerPort: 20000
        - containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: id
          value: "1"
        - name: _JAVA_OPTIONS
          value: "-Xmx256m -Xms256m"
        - name: module
          value: "all"
        - name: hostip
          value: "10.122.0.5"
        - name: profile
          value: "do1"
        - name: segment
          value: "chk3s"
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: http-service
  namespace: http  # Add namespace
spec:
  type: NodePort
  selector:
    app: http
  ports:
    - protocol: TCP
      port: 20000        # Internal port of the service
      targetPort: 20000   # Container's port
      nodePort: 32525     # External port on the node
      name: promethious
    - protocol: TCP
      port: 8080       # Internal port of the service
      targetPort: 8080   # Container's port
      nodePort: 32101     # External port on the node
      name: http
   

---
