services:
  intl:
    image: 10.122.0.2:5000/beacon:15nov2024
    environment: [
       id=1, _JAVA_OPTIONS=-Xmx256m -Xms256m,module=ic,hostip=10.122.0.5,segment=ch5,profile=do1,cluster=intl,priority=low]
    volumes: ['./logs:/opt/jboss/wildfly/logs'] 
    restart: always
    logging:
      driver: "none"
version: '3'

