apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkanode166
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkanode166
  template:
    metadata:
      labels:
        app: kafkanode166
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Exists"
        effect: "NoExecute"
      nodeSelector:
        kubernetes.io/hostname: kafka4 # Specify the node by its hostname
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "48"  # Set the retention time to 48 hours
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "10.122.0.4:30080"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://10.122.0.4:30091"  # NodePort for Kafka Node 1
        - name: KAFKA_LOG_DIRS
          value: "/bitnami/kafka/data"
        volumeMounts:
        - name: kafka-storage
          mountPath: /bitnami/kafka
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc-166
---
apiVersion: v1
kind: Service
metadata:
  name: kafkanode166-service
  namespace: kafka
spec:
  selector:
    app: kafkanode166
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30091 # NodePort for Kafka Node 1
  type: NodePort

