apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-166
  namespace: kafka
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka166
  hostPath:
    path: "/home/kafkadata"  # Adjust this path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kafkanode166 # Replace with the actual node name or label
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-167
  namespace: kafka
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka167
  hostPath:
    path: "/home/kafkadata"  # Adjust this path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kafkanode167 # Replace with the actual node name or label

