apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: kafka
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper166
  hostPath:
    path: "/home/zookeeperdata"  # Adjust the path on your node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kafkanode166  # Replace with the actual node where Zookeeper runs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: zookeeper166

